name: gestion_asistencia_docente
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  http: ^0.13.5  
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  geolocator: ^8.0.0
  shared_preferences: ^2.0.8
  video_player: ^2.2.12
  dio: ^4.0.0
  just_audio: ^0.9.26
  audio_waveforms: ^0.1.3
  flutter_pdfview: 1.3.2
  path_provider: ^2.0.11
  multi_select_flutter: ^4.0.0
  file_picker: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  material_design_icons_flutter: ^5.0.6595
  cupertino_icons: ^1.0.6
  firebase_messaging: ^15.1.3
  flutter_fortune_wheel: ^1.3.2
  confetti: ^0.6.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/utils/sidebar_fondo.jpg
    - assets/utils/splash.png
    - assets/utils/GestionAsis.jpg
    - assets/utils/image.png
    - assets/utils/login.png
    - assets/utils/logo.png
    - assets/utils/estudiar.png
    - assets/utils/desafiar.png
    - assets/utils/finalizado.png
    - assets/utils/user1.png
    - assets/utils/user2.png    


